[package]
name = "lesson-05"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
leptos = { version = "0.8.15", features = ["csr"] }
leptos_meta = "0.8.5"
meval = "0.2.0"
wasm-bindgen = "0.2.106"
